strings[48] = "W2-L16 Press "+ string(global.controlsinteract) +" on this weird particle thingy."
strings[56] = "W3-L2 If you are stuck, press "+ string(global.controlsrestart) +" to restart."
strings[130] = "SLIPPERY-L6 You can press "+ string(global.controlsinteract) +" to shoot with your gun."
strings[94] = "W4-L19 Oh, maybe you don't feel anything, since you've died like " + string(global.deaths) + " times."
strings[136] = "W5-L10 You got a gun! Press "+string(global.controlsinteract) + " to shoot, they can dodge bullets so beware."