image_blend = c_white
image_alpha = 1
image_xscale = 5
switch(global.hatselected) {
case(0): image_alpha = 0 break;
case(1): sprite_index = s_graduationhat break;
case(2): sprite_index = s_conehat break;
case(3): sprite_index = s_partyhat break;
case(4): sprite_index = s_paperhat break;
case(5): sprite_index = s_tophat break;
case(6): sprite_index = s_yellowtophat break;
case(7): image_blend = c_red
sprite_index = s_reddiehat break;
case(8): sprite_index = s_santahat break;
case(9): sprite_index = s_witchhat break;
case(10): sprite_index = s_pumpkinhat break;
case(11): sprite_index = s_brownhat break;
case(12): sprite_index = s_grayhat break;
case(13): sprite_index = s_whitehat break;
case(14): sprite_index = s_sunhat break;
case(15): sprite_index = s_redblockhat break;
case(16): sprite_index = s_yellowblockhat break;
case(17): sprite_index = s_greenblockhat break;
case(18): sprite_index = s_blueblockhat break;
case(19): sprite_index = s_whiteblockhat break;
case(20): sprite_index = s_spikehat break;
case(21): image_alpha = random_range(0.5,1)
sprite_index = s_spikehat break;
case(22): image_blend = c_lime
sprite_index = s_spikehat break;
case(23): image_blend = c_yellow
sprite_index = s_spikehat break;
case(24): sprite_index = s_hexagonhat break;
case(25): sprite_index = s_breadhat break;
case(26): image_xscale = 6.2
sprite_index = s_soldierhat break;
case(27): sprite_index = s_samuraihat break;
case(28): sprite_index = s_redbeaniehat break;
case(29): sprite_index = s_yellowbeaniehat break;
case(30): sprite_index = s_greenbeaniehat break;
case(31): sprite_index = s_bluebeaniehat break;
}